# Generated by Django 5.1.4 on 2024-12-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('assunto', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
