# Generated by Django 5.1.4 on 2024-12-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
        ('usuarios', '0003_topicoestudo_grupoestudo_materialestudo_sessaoestudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='juiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacoes', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='submissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='avaliacoes', to='hackathons.submissao'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desafios', to='hackathons.hackathon'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipes', to='hackathons.hackathon'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hackathons', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hackathons.equipe'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='participantes', to='hackathons.hackathon'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='desafio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissoes', to='hackathons.desafio'),
        ),
        migrations.AlterField(
            model_name='submissao',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submissoes', to='hackathons.equipe'),
        ),
    ]
