# Generated by Django 5.1.4 on 2025-02-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_remove_biblioteca_categoria_remove_biblioteca_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/imagens/'),
        ),
    ]
