# Generated by Django 5.1.4 on 2025-02-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_livro_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
