# Generated by Django 5.1.4 on 2025-02-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_livro_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='formato',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='idioma',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='secao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livro',
            name='total_paginas',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
