# Generated by Django 5.1.4 on 2025-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_livro_formato_livro_idioma_livro_secao_livro_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorialivro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/categoria/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='mostrar_preco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='resumo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorialivro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
