# Generated by Django 5.1.4 on 2024-12-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(max_length=255)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Bolsas de Estudo', 'Bolsas de Estudo'), ('Eventos', 'Eventos'), ('Notícias Educacionais', 'Notícias Educacionais')], max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/')),
            ],
        ),
    ]
