# Generated by Django 5.1.4 on 2024-12-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('usuarios', '0003_topicoestudo_grupoestudo_materialestudo_sessaoestudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios', to='forum.postagem'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='usuario_criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='forums_criados', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='postagens', to='forum.forum'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='postagens', to='usuarios.usuario'),
        ),
    ]
