# Generated by Django 5.1.4 on 2024-12-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('duracao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=100)),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online')], max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='instituicoes.instituicao')),
            ],
        ),
    ]
