# Generated by Django 5.1.4 on 2024-12-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('instituicoes', '0002_categoria_status_rename_endereco_instituicao_senha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursos', to='instituicoes.instituicao'),
        ),
    ]
