# Generated by Django 5.1.4 on 2025-01-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_categoria_curso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_cursos/'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
