# Generated by Django 5.1.4 on 2025-01-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_imagem_alter_curso_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
