# Generated by Django 5.1.4 on 2025-01-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_curso_data_criacao'),
        ('instituicoes', '0004_curso_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField()),
                ('titulo', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='instrutores/')),
                ('cursos', models.IntegerField()),
                ('estudantes', models.IntegerField()),
                ('avaliacao', models.FloatField()),
                ('especializacoes', models.TextField()),
                ('contato', models.CharField(max_length=255)),
                ('instrutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cursos.instrutor')),
            ],
        ),
    ]
