# Generated by Django 5.1.4 on 2025-03-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_instrutor_perfilinstrutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
