# Generated by Django 5.1.4 on 2025-03-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_tipo_usuario_perfilusuario_delete_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
