# Generated by Django 5.1.4 on 2024-12-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Escola', 'Escola'), ('Centro de Formação', 'Centro de Formação')], max_length=100)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField(blank=True, null=True)),
                ('data_fundacao', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='centros/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CentrosImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='Centros/imagens/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='instituicoes.centros')),
            ],
        ),
    ]
