# Generated by Django 5.1.4 on 2024-12-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
        ('usuarios', '0002_habilidade_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='endereco',
            new_name='senha',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='data_fundacao',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='site',
        ),
        migrations.RemoveField(
            model_name='instituicao',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('numero_vagas', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.categoria')),
                ('instituicoes', models.ManyToManyField(related_name='cursos_oferecidos', to='instituicoes.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.URLField(blank=True, null=True)),
                ('data_fundacao', models.DateField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='instituicoes/logos/')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='instituicoes.instituicao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.categoria')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.status')),
            ],
        ),
        migrations.CreateModel(
            name='DadosUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('perfil_instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituicoes.perfilinstituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to='instituicoes.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='SeguirInstituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_seguindo', models.DateTimeField(auto_now_add=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='instituicoes.instituicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instituicoes_seguidas', to='usuarios.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='InstituicaoImagem',
        ),
    ]
