# Generated by Django 5.1.4 on 2024-12-28 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0002_categoria_status_rename_endereco_instituicao_senha_and_more'),
        ('usuarios', '0003_topicoestudo_grupoestudo_materialestudo_sessaoestudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.categoria'),
        ),
        migrations.AlterField(
            model_name='dadosupload',
            name='perfil_instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.perfilinstituicao'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='perfilinstituicao',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil', to='instituicoes.instituicao'),
        ),
        migrations.AlterField(
            model_name='perfilinstituicao',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.status'),
        ),
        migrations.AlterField(
            model_name='perfilinstituicao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instituicoes.categoria'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='postagens', to='instituicoes.instituicao'),
        ),
        migrations.AlterField(
            model_name='seguirinstituicao',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seguidores', to='instituicoes.instituicao'),
        ),
        migrations.AlterField(
            model_name='seguirinstituicao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instituicoes_seguidas', to='usuarios.usuario'),
        ),
    ]
